### ISSUE TITLE
Support mdbook-quiz addon

### ISSUE THREAD

**Issue by uncenter** [catppuccin/mdBook#105]
Support https://github.com/cognitive-engineering-lab/mdbook-quiz. Should be as simple as:

```css
.mdbook-quiz .answer .answer-row > div {
  .correct::before {
    color: @green;
  }
  .incorrect:before {
    color: @red;
  }
}
```

Though not sure if it should go in the main file or separately like it is for the admonish plugin.
